# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Please < Formula
  desc "A natural language interface for your terminal"
  homepage "https://github.com/iishyfishyy/please"
  version "1.0.5"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/iishyfishyy/please/releases/download/v1.0.5/please_1.0.5_Darwin_x86_64.tar.gz"
      sha256 "24bc459259174616955d837fabb2aeb5f5bf743cd1bd83b45d28e2768f13efae"

      def install
        bin.install "please"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/iishyfishyy/please/releases/download/v1.0.5/please_1.0.5_Darwin_arm64.tar.gz"
      sha256 "b17acfb98a6aec27dbbd22532462e9e09c8a755b47127e22f2afbe1d293fe764"

      def install
        bin.install "please"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/iishyfishyy/please/releases/download/v1.0.5/please_1.0.5_Linux_x86_64.tar.gz"
      sha256 "7cc4a4d1d4d5b8fc8140689b661768df3b6fe9c2d5bebc5f5fdd445569400d7a"
      def install
        bin.install "please"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/iishyfishyy/please/releases/download/v1.0.5/please_1.0.5_Linux_arm64.tar.gz"
      sha256 "a0b8e77df49a40354430d935a0dd4da05640e058d88cf5d7c6f50e42ae44cdbc"
      def install
        bin.install "please"
      end
    end
  end

  test do
    system "#{bin}/please", "--version"
  end
end
